### ISSUE TITLE
1.0 release steps

### ISSUE THREAD

**Issue by blinky3713** [f-o-a-m/purescript-web3#103]
This is a place to list issues before a 1.0 release, the target for this is July 1. Websocket support is not a blocker for this, but it would be nice.

- [x] #98 
- [x] #97 
- [x] #96

**Comment by XertroV** [comment]
Re websockets, is there a good implementation in Purescript? Had a look a few months ago and didn't find anything that seemed good for both browser+server :/

**Comment by safareli** [comment]
We use [purescript-websocket-simple](https://github.com/zudov/purescript-websocket-simple)

**Comment by XertroV** [comment]
@safareli - Thanks!
