### ISSUE TITLE
Investigate "can receive multiple events in the correct order" failure

### ISSUE THREAD

**Issue by safareli** [f-o-a-m/purescript-web3#134]
this test failed on totally unrelated case change https://github.com/f-o-a-m/purescript-web3/pull/133 and is very strange as both values on the left and right side of are same
https://travis-ci.org/f-o-a-m/purescript-web3/builds/593743530#L2403
```
Multifilter

  ✗ can receive multiple events in the correct order:

  [(Tuple 58 2),(Tuple 58 3),(Tuple 58 4),(Tuple 58 5),(Tuple 58 6),(Tuple 58 7),(Tuple 58 8),(Tuple 58 9),(Tuple 58 10),(Tuple 58 11)] = [(Tuple 58 2),(Tuple 58 3),(Tuple 58 4),(Tuple 58 5),(Tuple 58 6),(Tuple 58 7),(Tuple 58 8),(Tuple 58 9),(Tuple 58 10),(Tuple 58 11)]

Summary

73/74 tests passed

```

**Comment by blinky3713** [comment]
I'm going to close this because they actually are the same and I've never seen this happen since we posted this issue
