### ISSUE TITLE
Monorepo with purescript-web3-generator

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/purescript-web3#144]
This is now possible with spago. It makes sense to monorepo these two to reduce the updates required in the full web3 stack -- basically every time we update web3-generator to a major version it's because we updated web3 to a major version

**Comment by blinky3713** [comment]
waiting on a reply to https://discourse.purescript.org/t/how-do-i-depend-on-multiple-packages-from-a-monorepo/2219

**Comment by blinky3713** [comment]
made an issue on spago's repo
https://github.com/purescript/spago/issues/758
