### ISSUE TITLE
Update to PS 0.14?

### ISSUE THREAD

**Issue by jetaggart** [f-o-a-m/purescript-web3#145]
Hey, just wondering if you all are planning on updating to 0.14? I might take a stab at it, but want to check in case I'm duplicating work.

**Comment by blinky3713** [comment]
We just haven’t gotten around to it, but help is welcome! We’d need to do the entire suite which is spread across a few packages that would be mono-repod if spago allowed it:

- purescript-eth-core
- purescript-web3
- purescript-web3-generator
- purescript-chanterelle (technically optional, but nice to have)

**Comment by kejace** [comment]
This is all done now. A link to the announcement I made on discourse:

https://discourse.purescript.org/t/purescript-web3-support-for-v0-14/2472
