### ISSUE TITLE
Add signing and recovery of messages

### ISSUE THREAD

**Issue by kejace** [f-o-a-m/purescript-web3#22]
See https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#sign
and https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#ecrecover

This would be very handy for interacting with state-channel contracts.

Also relevant is `signTypedData` which is the `EIP712` proposal (https://github.com/ethereum/EIPs/pull/712). See https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290 for context.

**Comment by blinky3713** [comment]
I'm not sure if this is even available as of today, can you try to find relevant code snippets from metamask?
