### ISSUE TITLE
Detecting if metamask is available

### ISSUE THREAD

**Issue by biern** [f-o-a-m/purescript-web3#23]
So, I'm trying to use a metamask provider and fallback to HttpProvider in case it's not available.

FFI function signature says that `metamaskProvider` always returns a `Provider` type, but that seems to be incorrect, since it does `return new Error(...)` when metamask is not available.
In consequence, using `metamask` as a provider throws `provider.sendAsync is not a function` in every call when metamask is not available.

Is there something that I'm missing or misusing? How could I check if metamask is available using the API provided besides just making a call and checking if it fails?

**Comment by blinky3713** [comment]
We've also experienced this difficulty when launching event watchers before metamasks finishes injecting it's `Web3` object. Clearly the `metamaskProvider` function should include an `Exception` in it's effects type. 

I haven't spent much time thinking about how to fix this problem, but in my mind the provider accessing should probably be wrapped in `Aff` to allow for the possibility of polling with timeout plus exceptions. Let's see what the solution is to #24
