### ISSUE TITLE
Dependency on Web3.js

### ISSUE THREAD

**Issue by biern** [f-o-a-m/purescript-web3#25]
Hi, it seems that dependency on Web3.js is added just to be able to create a HttpProvider. If that's the case than it could possibly be swapped for something much more more lightweight. 

Bundle size after browserifying:
- `web3` - 1.1MB
- `web3-http-provider` ~300KB
- `ethjs-provider-http` - ~4KB

**Comment by blinky3713** [comment]
This sounds great. Can you make an argument for or against using `web3-http-provider` vs `ethjs-provider-http` in terms of features?

**Comment by biern** [comment]
My experience with `ethjs-provider-http` is quite limited unfortunately. It's used internally by `ethjs` and is advertised to follow the web3 provider specification. I'm also successfully using it in a side project but that's not anything battle tested.
Also, since the http provider is not tightly bound to the `purescript-web3`, maybe it could just be migrated into a micro library of its own? Then any implementation could be passed in by the `purescript-web3` user.

**Comment by blinky3713** [comment]
It looks like with the release of web3-js 1.0 there will be a (sub-package for the http provider) [https://github.com/ethereum/web3.js/tree/1.0/packages/web3-providers-http]. Maybe we should just use that?

**Comment by blinky3713** [comment]
switched to ethjs-provider-http

https://github.com/f-o-a-m/purescript-web3/commit/ba8925e5bc3f006e740723b3c84af8c328009089
