### ISSUE TITLE
[Discussion] Migrating to / supporting `psc-package`

### ISSUE THREAD

**Issue by XertroV** [f-o-a-m/purescript-web3#67]
I recently wanted to port a package I'm working on to `psc-package` to avoid using bower.

Some of the web3 dependencies aren't on `psc-package` yet, though I've currently got a build working with all deps (and some extras) over at github.com/secure-vote/package-sets including v0.11.4 of purescript-web3 (bc I haven't updated to 0.15 yet, wanted to get psc-package working first).

@blinky3713 - is this something you'd be interested in having for the package? Personally I feel like `psc-package` is a big improvement over `bower`, though it'd be nice to eventually see dependencies identified via hash and supporting >1 version of a package too (maybe supported by IPFS 😄)

**Comment by blinky3713** [comment]
We used to use psc-package for this library, but an internally curated one, and we stoped. we use psc-package for all internal applications at FOAM, but we're not interested in using it at this time for libraries until it's a little bit more mature.

**Comment by XertroV** [comment]
Cool - will be sure to mention if I have any problems. 

I'm going to try and work on getting our dependencies (about 20 in total) in to psc-package slowly, either by making PRs to various libs or forking and maintaining some myself that are either old or abandoned.

That should help get things prepped if/when you do want to add psc-package support - also, I think you can have bower and psc-package in parallel (though not sure of complexities around this)

**Comment by safareli** [comment]
@XertroV for a lib to be in package set it's not required to have psc-package.json.
so you can take "depends" from [psc-package.json](https://github.com/f-o-a-m/purescript-web3/blob/bd3a88ef12864eb9fa1d03057f1f4f85a9a776aa/psc-package.json#L5-L23) and add it to any package set as long as you are able to build it.
