### ISSUE TITLE
difficult to create block number

### ISSUE THREAD

**Issue by XertroV** [f-o-a-m/purescript-web3#71]
Creating a `BlockNumber` is a bit difficult, only way I can see atm is 

`BN $ wrap $ embed 1000`

The `wrap` is only usable bc of the deriving newtype. Is there another way that's intended?

Note, this would be solved by exporting `BlockNumber` constructor, which feels like the better option to me.

**Comment by blinky3713** [comment]
I'm not sure if there was a particular design decision there, but for the record, it would be _even longer_ if you did use the type constructor

```
BN $ BlockNumber $ embed 1000
```

There is an outstanding issue for more global exports, or a better organizational scheme, you can link this there. Things like this will come in before we do an official 1.0 release.

**Comment by XertroV** [comment]
Ahh yeah - _length_ doesn't bother me, more just how intuitive it is to find out _how_ to do it in the first place.

Noted re global exports - probs the right way to go then. (On that note, I noticed HexString constructor is exported atm, which we probably _don't_ want)

**Comment by blinky3713** [comment]
The `HexString` constructor is currently used by the generator when making event filters, although that could be changed to use `unsafePartial fromJust <<< mkHexString`.  It used to be used in more places, though not anymore. Can try to get this when I get a minute.

**Comment by XertroV** [comment]
That makes sense, but I think `unsafePartial` is better (since we know the generator will make valid hexstrings anyway). The concern from my end is that by exposing `HexString` it's possible to create _invalid_ hexstrings, which  is why `mkHexString` exists at all. So better not to expose `HexString`. I guess it's not _that_ big of a deal, but it does break the type safety.
