### ISSUE TITLE
Library does not work with Kovan

### ISSUE THREAD

**Issue by XertroV** [f-o-a-m/purescript-web3#72]
So I've just discovered the library doesn't work with Kovan (to some degree)

Particularly the `Block` objects can't be created bc there's no `nonce` given in the returned block objects

Personally working with kovan is pretty important since it's much nicer than ropsten to work with.

Not sure how best this would be fixed.

**Comment by blinky3713** [comment]
It seems Kovan does have a nonce on their block object, which should come back as a hex string

https://kovan.etherscan.io/block/6454736

curious that you are getting an error.

**Comment by XertroV** [comment]
If you query a parity node that's actually the `author` field I think. Not sure if hacking that in is a good idea though. Does mean the block type is consistent though.

**Comment by blinky3713** [comment]
yeah, there might be a larger discussion at some point about how to compensate for these differences. for the moment, i'm not inclined to do anything about it because it's definitely the exception, not the rule. rinkeby and main net still adhere to the format specified in the yellow paper.

**Comment by XertroV** [comment]
Hmm, it's a bit annoying for me because I use Kovan for testing. I might maintain a fork w/ the author-as-nonce thing. TBH this doesn't feel too bad a solution, it's only a small implementation detail and most ppl won't care about nonces, and if they do they won't be using kovan. If they care about authors on Kovan then they can just read the docs to see that it's the 'nonce' field, which is already consistent with how etherscan does it (and means minimal code-base changes)
